------------------------------------------------------------------------------------------------------------------------------
TABLES AND FIGURES
------------------------------------------------------------------------------------------------------------------------------

#PRE-CLUSTERING

#Exported plots as PNGs through RStudio

#Read in pre-filter quality control data generated by ArchR

`510-Pre-Filter-Metadata` <- readRDS("~/QualityControl/510/510-Pre-Filter-Metadata.rds")
`611-Pre-Filter-Metadata` <- readRDS("~/QualityControl/611/611-Pre-Filter-Metadata.rds")
`993-Pre-Filter-Metadata` <- readRDS("~/QualityControl/993/993-Pre-Filter-Metadata.rds")

#Table 1: Preclustering QC summary for donors---------------------------------------------------------------------------------

table_precluster_A <- data.frame(
"Sample" = "510",
"Cells_Passed_QC" = sum(`510-Pre-Filter-Metadata`$Keep),
"Cells_Failed_QC" = sum(`510-Pre-Filter-Metadata`$Keep == 0),
"Total_Frags" = sum(`510-Pre-Filter-Metadata`$nFrags),
"Median_Frags" = median(`510-Pre-Filter-Metadata`$nFrags[`510-Pre-Filter-Metadata`$Keep ==1]),
"Median_TSS_Enrichment" = median(`510-Pre-Filter-Metadata`$TSSEnrichment[`510-Pre-Filter-Metadata`$Keep == 1])
)

newrow_precluster_A <- data.frame(
"Sample" = "611",
"Cells_Passed_QC" = sum(`611-Pre-Filter-Metadata`$Keep),
"Cells_Failed_QC" = sum(`611-Pre-Filter-Metadata`$Keep == 0),
"Total_Frags" = sum(`611-Pre-Filter-Metadata`$nFrags),
"Median_Frags" = median(`611-Pre-Filter-Metadata`$nFrags[`611-Pre-Filter-Metadata`$Keep ==1]),
"Median_TSS_Enrichment" = median(`611-Pre-Filter-Metadata`$TSSEnrichment[`611-Pre-Filter-Metadata`$Keep == 1])
)
table_precluster_A <- rbind(table_precluster_A, newrow_precluster_A)

newrow_precluster_A <- data.frame(
"Sample" = "993",
"Cells_Passed_QC" = sum(`993-Pre-Filter-Metadata`$Keep),
"Cells_Failed_QC" = sum(`993-Pre-Filter-Metadata`$Keep == 0),
"Total_Frags" = sum(`993-Pre-Filter-Metadata`$nFrags),
"Median_Frags" = median(`993-Pre-Filter-Metadata`$nFrags[`993-Pre-Filter-Metadata`$Keep ==1]),
"Median_TSS_Enrichment" = median(`993-Pre-Filter-Metadata`$TSSEnrichment[`993-Pre-Filter-Metadata`$Keep == 1])
)
table_precluster_A <- rbind(table_precluster_A, newrow_precluster_A)

#Table 2: Count table for doublet removal-------------------------------------------------------------------------------------

`510-Doublet-Summary` <- readRDS("C:/Users/Tom/Desktop/single_cell/QualityControl/510/510-Doublet-Summary.rds")
`611-Doublet-Summary` <- readRDS("C:/Users/Tom/Desktop/single_cell/QualityControl/510/510-Doublet-Summary.rds")
`993-Doublet-Summary` <- readRDS("C:/Users/Tom/Desktop/single_cell/QualityControl/510/510-Doublet-Summary.rds")

table_doubletremoval_B <- data.frame(
"Sample" = c("510", "611", "993"),
"Cell_Count_Pre_Doublet_Removal" = c("8321","5029","2287"),
"Cell_Count_Post_Doublet_Removal" = c("7629","5029","2235"),
"Percentage_of_Cells_Removed_per_Donor" = c("8.3%","0%","2.3%")
)

#Plot 1: TSS Enrichment vs log10(number of unique fragments)------------------------------------------------------------------

df <- getCellColData(project, select = c("log10(nFrags)", "TSSEnrichment"))

df611 <- df[grep("611", rownames(df)), ]
df510 <- df[grep("510", rownames(df)), ]
df993 <- df[grep("993", rownames(df)), ]

plot611_1 <- ggPoint(
     x = df611[,1], 
     y = df611[,2], 
     colorDensity = TRUE,
     continuousSet = "sambaNight",
     xlabel = "Log10 Unique Fragments",
     ylabel = "TSS Enrichment",
     xlim = c(log10(500), quantile(df[,1], probs = 0.99)),
     ylim = c(0, quantile(df[,2], probs = 0.99))
 ) + geom_hline(yintercept = 4, lty = "dashed") + geom_vline(xintercept = 3, lty = "dashed")
 
 plot510_1 <- ggPoint(
    x = df510[,1], 
    y = df510[,2], 
    colorDensity = TRUE,
    continuousSet = "sambaNight",
    xlabel = "Log10 Unique Fragments",
    ylabel = "TSS Enrichment",
    xlim = c(log10(500), quantile(df[,1], probs = 0.99)),
    ylim = c(0, quantile(df[,2], probs = 0.99))
) + geom_hline(yintercept = 4, lty = "dashed") + geom_vline(xintercept = 3, lty = "dashed")

plot993_1 <- ggPoint(
    x = df993[,1], 
    y = df993[,2], 
    colorDensity = TRUE,
    continuousSet = "sambaNight",
    xlabel = "Log10 Unique Fragments",
    ylabel = "TSS Enrichment",
    xlim = c(log10(500), quantile(df[,1], probs = 0.99)),
    ylim = c(0, quantile(df[,2], probs = 0.99))
) + geom_hline(yintercept = 4, lty = "dashed") + geom_vline(xintercept = 3, lty = "dashed")

#Ridge plot for TSS enrichment per donor--------------------------------------------------------------------------------------

#Batch corrected data used for pre clustering with filtering

Ridge_plot_E <- plotGroups(
     ArchRProj = project_batch_corrected,
     groupBy = "Sample",
     colorBy = "cellColData",
     name = "TSSEnrichment",
     plotAs = "ridges"
 )
 
#Fragment size plot-----------------------------------------------------------------------------------------------------------

plot_fragmentsizes_precluster <- plotFragmentSizes(project_batch_corrected)

#POST-CLUSTERING--------------------------------------------------------------------------------------------------------------

#Cell counts per cluster per donor--------------------------------------------------------------------------------------------
table_cell_per_cluster <- as.matrix(confusionMatrix(project_cluster$Sample, project_cluster$Clusters)

#Cell counts per cluster------------------------------------------------------------------------------------------------------
#Janitor package will be used for data frame editing
install.packages("janitor")
library(janitor)
#Make data frame copy of table containing number of cells per cluster per donor
table_cell_cluster_all <- as.data.frame(table_cell_per_cluster)
#Move rownames to column as use of adorn_totals creates a "Total" cell which shifts data
setDT(table_cell_cluster_all, keep.rownames = TRUE)[]
#Use janitor feature to apply new row to data frame containing totals
table_cell_cluster_all %<>% adorn_totals(dat = table_cell_cluster_all, where = "row")
#Remove rows containing donor specific data and column containing "Total" cell
table_cell_cluster_all <- table_cell_cluster_all[-c(1,2,3), ]
table_cell_cluster_all <- table_cell_cluster_all[,-1]
                                    
#UMAPs------------------------------------------------------------------------------------------------------------------------
#IterativeLSI UMAP------------------------------------------------------------------------------------------------------------
project_cluster <- addUMAP(
    ArchRProj = project_cluster,
    reducedDims = "IterativeLSI",
    name = "UMAP",
    nNeighbors = 30,
    minDist = 0.5,
    metric = "cosine"
)
plot_UMAP_by_cluster <- plotEmbedding(ArchRProj = project_cluster, colorBy = "cellColData", name = "Clusters", embedding = "UMAP")
plot_UMAP_by_donor <- plotEmbedding(ArchRProj = project_cluster, colorBy = "cellColData", name = "Sample", embedding = "UMAP")

#Harmony UMAP-----------------------------------------------------------------------------------------------------------------

project_cluster <- addUMAP(
    ArchRProj = project_cluster,
    reducedDims = "Harmony",
    name = "UMAP",
    nNeighbors = 30,
    minDist = 0.5,
    metric = "cosine"
)
plot_UMAP_by_cluster_harmony <- plotEmbedding(ArchRProj = project_cluster, colorBy = "cellColData", name = "Clusters", embedding = "UMAP")
plot_UMAP_by_donor_harmony <- plotEmbedding(ArchRProj = project_cluster, colorBy = "cellColData", name = "Sample", embedding = "UMAP")

------------------------------------------------------------------------------------------------------------------------------
